global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: arbitrage-engine-clob-hft
    static_configs:
      - targets: ["bot-clob-hft:9108"]
  - job_name: arbitrage-engine-quote-arb
    static_configs:
      - targets: ["bot-quote-arb:9109"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
